[package]
name = "inflect"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
ndarray = "0.16.1"
ndarray-linalg = { version = "0.17.0", features = ["openblas-static"] }
ort = "2.0.0-rc.9"
tokenizers = "0.21.1"
